### ISSUE TITLE
Sanitizer njefunguje

### ISSUE THREAD

**Issue by zobadaniel** [fscholze/uploader-recny-model-server#5]
Witaj,

sym ći móžnosć zatwarił, přepruwować, hač sanitizer funguje. Pola mnje njeje šło, někak je so posledni dypk před kóncowki dataje wotstronił a tak běše potom cyła logika na kruchi.

**Comment by fscholze** [comment]
Ach mist, trechi. Je cylu dataju prepruwowal...
