### ISSUE TITLE
Dataja kotraz z create_transcripta prindze ma 2 koncowki

### ISSUE THREAD

**Issue by fscholze** [fscholze/uploader-recny-model-server#7]
Hdyz dataja file.mp4 reka prindze dataja z scripta jako file.mp4.srt won. Je to ok?

**Comment by zobadaniel** [comment]
Haj, to je ok. Prjedy hač spytamy kóncowku hódać abo tak, radšo něšto připójsnjemy. Samo program "Subtitle Edit" je mudre dosć, to spóznać.

**Comment by fscholze** [comment]
Ok, dokelz sym netko preco tun koncowku prec zwal a so za dataja.srt na priklad prasal. To je naprklad prez:
$ filename=foo.txt
$ echo "${filename%.*}"
foo
mozno

**Comment by zobadaniel** [comment]
Ale funguje ta logika hišće, hdyž něchto dataju bjez někajkej kóncowki horjelodwje? 

Hewak móžemy to rady tak činić, něhdźe sym tón trik tež hižo raz wužiwał.

Njech sebi to spomjatkujemoj za pozdźišo ("porjeńšenja"), wostanjemy tón issue wočinjene.
