### ISSUE TITLE
numpy pobrachuje

### ISSUE THREAD

**Issue by fscholze** [fscholze/uploader-recny-model-server#8]
Hdyz sej wuzwolu Bozu_Msu, dostanu tuton zmylk, dokelz njeje python instalowane. Je to ok dokelz program na serveru pola tebje lezi a python a numpy globalne installowane su, abo by jen to hisce raz polepsic dybjal?

`{
  stderr: 'src/scripts/create_transcript.sh: line 79: ffmpeg: command not found\n' +
    'src/scripts/create_transcript.sh: line 80: soxi: command not found\n' +
    'src/scripts/create_transcript.sh: line 84: sox: command not found\n' +
    'src/scripts/create_transcript.sh: line 86: /proprietary/testrec: No such file or directory\n' +
    'Traceback (most recent call last):\n' +
    '  File "/Users/feliksscholze/Desktop/sst/uploader/uploader-recny-model-server/src/scripts/log2srt.py", line 2, in <module>\n' +
    '    import numpy as np\n' +
    "ModuleNotFoundError: No module named 'numpy'\n" +
    'mv: rename uploads/0c81e0a5feeb883027421df985247f90/*.srt to uploads/0c81e0a5feeb883027421df985247f90/beitragsbescheid.pdf.srt: No such file or directory\n',
  stdout: 'Dataja=uploads/0c81e0a5feeb883027421df985247f90/beitragsbescheid.pdf\n' +
    'Postup=uploads/0c81e0a5feeb883027421df985247f90/progress.txt\n' +
    'Rjadowak=0c81e0a5feeb883027421df985247f90\n' +
    'Model=BOZA_MSA\n' +
    'Format=srt\n' +
    '----> HOTOWE <----\n'
}`

**Comment by zobadaniel** [comment]
Hdyž backend pola tebi lokalnje běži, jenož simulator funguje. Tebi nimo python hišće tójšto dalšich programow faluje: ffmpeg, sox, soxi - a wězo tón spóznawanski program wot FHG, kiž njesměm wozjewić.

Abo přestajiš w twojej config backend URL na "https://transcripts.serbski-inkubator.de/" - potom móžeš znajmjeńša z twojim lokalnym frontend dźěłać.
